Add led subsystem
chopshop-166/frc-2023 pull request #6
Opened 2023-01-21 21:40 UTC by Liammurray19

commands are 
- colorAlliance
- setYellow
- setPurple

2023-01-21 22:01 UTC, msoucy requested changes

2023-01-21 22:01 UTC, msoucy commented on build.gradle
> +    id "edu.wpi.first.GradleRIO" version "2023.2.1"
`2023.2.2` please

2023-01-21 22:01 UTC, msoucy commented on .vscode/launch.json
> +    {
How did this get here?

2023-01-21 22:01 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +import java.util.PrimitiveIterator.OfInt;
How did this get here?

2023-01-21 22:01 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +import javax.annotation.meta.When;
How did this get here?

2023-01-21 22:01 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +    private Led led = new Led(map.getLedMap());
This should be after the `$Subsystems$` marker

2023-01-21 22:01 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Led.java
> +    private int R;
Normally I'd say "these should be lowercase" but they don't actually seem to be used anyways?

2023-01-21 22:01 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Led.java
> +    private Led defaultColor;
Is `defaultColor` used?

2023-01-21 22:01 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Led.java
> +        led.setData(ledBuffer);
This still sketches me out that it's *after* the for loop setting the variables...

2023-01-27 21:26 UTC, JoeJanickiChSh commented on src/main/java/frc/robot/subsystems/Led.java
> +        for (var i = 0; i < ledBuffer.getLength(); i++) {
This loop in the constructor does not need to be here

2023-01-27 21:32 UTC, JoeJanickiChSh commented on src/main/java/frc/robot/subsystems/Led.java
> -        led.start();
keep the start

2023-01-27 21:35 UTC, JoeJanickiChSh approved these changes

2023-02-01 00:26 UTC, msoucy requested changes

2023-02-01 00:26 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +        controller.a().onTrue(led.setYellow());
Let's not assign these to buttons for now?

2023-02-01 00:26 UTC, msoucy commented on src/main/java/frc/robot/maps/RobotMap.java
> +    LedMap led;
Don't really need this line

2023-02-01 00:26 UTC, msoucy commented on src/main/java/frc/robot/maps/subsystems/LedMap.java
> +    public LedMap(AddressableLED led, AddressableLEDBuffer ledBuffer) {
It would be kind of nice if we could pass in just the port number and buffer size, and have the map create it automatically?

2023-02-01 00:26 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Led.java
> +        return cmd("Set to Alliance Color").onExecute(() -> {
Should this be `onExecute`? Once it sets colors, the LEDs will stay on those colors until they're changed.

2023-02-01 01:32 UTC, msoucy approved these changes

2023-02-01 01:33 UTC, merged