Smart dashboard buttons
chopshop-166/frc-2023 pull request #74
Opened 2023-11-10 01:16 UTC by Liammurray19

Created buttons on the smart dashboard for the drive testing. Got rid of the button maps on the drive controller to prevent accidental usage

2023-11-10 16:04 UTC, bot190 reviewed
Awesome! Now can you look into automatic placing the buttons on  new tab? I believe we have examples of this in the 2022 code

2023-11-12 19:42 UTC, msoucy requested changes

2023-11-12 19:42 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
>          /*
Can you remove this block as well?

2023-11-24 16:47 UTC, bot190 commented on src/main/java/frc/robot/Robot.java
> +        Shuffleboard.getTab("Pit Test").add("Drive Forward", drive.moveForDirectional(0, -1, 5));
Awesome,now can you specify a layout for these so they make a plus shape? Maybe make the center a stop button?

2024-01-03 04:14 UTC, bot190 approved these changes

2024-01-03 04:21 UTC, merged